# Generated by Django 5.2.7 on 2025-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp_path',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
