# Generated by Django 5.2.7 on 2025-10-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventusers',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
