# Generated by Django 5.2.6 on 2025-12-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventusers_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='eventusers',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventusers',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
