# Generated by Django 5.2.6 on 2025-11-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_categories_tags_alter_event_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
