# Generated by Django 5.2.6 on 2025-11-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_owner_id_event_owner'),
        ('users', '0005_rename_password_hash_user_password_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='forumcomments',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
