# Generated by Django 5.2.6 on 2025-11-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_forum_owner_id_alter_forumcomments_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.TextField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
