# Generated by Django 5.2.6 on 2025-11-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_name_event_title_remove_event_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
